//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int CopyID { get; set; }
        public int SSN { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Copy Copy { get; set; }
        public virtual Member Member { get; set; }
    }
}
