//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Migrations;

    public partial class GTLEntities : DbContext
    {
        public GTLEntities(): base("name=GTLEntities")
        {
            Seed();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private void Seed()
        {
            #region Clear all info
            //this.Database.ExecuteSqlCommand("EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'");
            this.Database.ExecuteSqlCommand("EXEC sp_MSForEachTable 'DELETE FROM ?'");
            //this.Database.ExecuteSqlCommand("EXEC sp_MSForEachTable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'");
            #endregion

            this.Addresses.AddOrUpdate(
                new Address { City = "Aalborg", PostalCode = 9200, Street = "Nibevej", Number = 12},
                new Address { City = "Aalborg", PostalCode = 9200, Street = "Sofiendalsvej", Number = 60},
                new Address { City = "Berlin", PostalCode = 10117, Street = "In den Ministergärten"}
            );

            this.SaveChanges();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Borrow> Borrows { get; set; }
        public virtual DbSet<Copy> Copies { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<LibrarianType> LibrarianTypes { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberCard> MemberCards { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
