//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public int SSN { get; set; }
        public string TypeName { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual LibrarianType LibrarianType { get; set; }
    }
}
