//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int SSN { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int Phone { get; set; }
        public string Password { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Member Member { get; set; }
    }
}
