//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlWebsite.CopyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CopyServiceReference.ICopyService")]
    public interface ICopyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetAvailableCopyId", ReplyAction="http://tempuri.org/ICopyService/GetAvailableCopyIdResponse")]
        int GetAvailableCopyId(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetAvailableCopyId", ReplyAction="http://tempuri.org/ICopyService/GetAvailableCopyIdResponse")]
        System.Threading.Tasks.Task<int> GetAvailableCopyIdAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetTotalNrCopies", ReplyAction="http://tempuri.org/ICopyService/GetTotalNrCopiesResponse")]
        int GetTotalNrCopies(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetTotalNrCopies", ReplyAction="http://tempuri.org/ICopyService/GetTotalNrCopiesResponse")]
        System.Threading.Tasks.Task<int> GetTotalNrCopiesAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetOutOnLoan", ReplyAction="http://tempuri.org/ICopyService/GetOutOnLoanResponse")]
        int GetOutOnLoan(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/GetOutOnLoan", ReplyAction="http://tempuri.org/ICopyService/GetOutOnLoanResponse")]
        System.Threading.Tasks.Task<int> GetOutOnLoanAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/DeleteCopy", ReplyAction="http://tempuri.org/ICopyService/DeleteCopyResponse")]
        bool DeleteCopy(int ssn, int copyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopyService/DeleteCopy", ReplyAction="http://tempuri.org/ICopyService/DeleteCopyResponse")]
        System.Threading.Tasks.Task<bool> DeleteCopyAsync(int ssn, int copyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICopyServiceChannel : GtlWebsite.CopyServiceReference.ICopyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CopyServiceClient : System.ServiceModel.ClientBase<GtlWebsite.CopyServiceReference.ICopyService>, GtlWebsite.CopyServiceReference.ICopyService {
        
        public CopyServiceClient() {
        }
        
        public CopyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CopyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CopyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CopyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAvailableCopyId(string isbn) {
            return base.Channel.GetAvailableCopyId(isbn);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableCopyIdAsync(string isbn) {
            return base.Channel.GetAvailableCopyIdAsync(isbn);
        }
        
        public int GetTotalNrCopies(string isbn) {
            return base.Channel.GetTotalNrCopies(isbn);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalNrCopiesAsync(string isbn) {
            return base.Channel.GetTotalNrCopiesAsync(isbn);
        }
        
        public int GetOutOnLoan(string isbn) {
            return base.Channel.GetOutOnLoan(isbn);
        }
        
        public System.Threading.Tasks.Task<int> GetOutOnLoanAsync(string isbn) {
            return base.Channel.GetOutOnLoanAsync(isbn);
        }
        
        public bool DeleteCopy(int ssn, int copyId) {
            return base.Channel.DeleteCopy(ssn, copyId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCopyAsync(int ssn, int copyId) {
            return base.Channel.DeleteCopyAsync(ssn, copyId);
        }
    }
}
