//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int CopyID { get; set; }
        public int SSN { get; set; }
        public System.DateTime FromDate { get; set; }
        public bool noticeSent { get; set; }
    
        public virtual Borrow Borrow { get; set; }
    }
}
