//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlWebsite.MaterialServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialServiceReference.IMaterialService")]
    public interface IMaterialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DoWork", ReplyAction="http://tempuri.org/IMaterialService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DoWork", ReplyAction="http://tempuri.org/IMaterialService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/GetMaterials", ReplyAction="http://tempuri.org/IMaterialService/GetMaterialsResponse")]
        bool GetMaterials(string materialTitle, string author, int numOfRecords, int isbn, int jobStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/GetMaterials", ReplyAction="http://tempuri.org/IMaterialService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<bool> GetMaterialsAsync(string materialTitle, string author, int numOfRecords, int isbn, int jobStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialServiceChannel : GtlWebsite.MaterialServiceReference.IMaterialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialServiceClient : System.ServiceModel.ClientBase<GtlWebsite.MaterialServiceReference.IMaterialService>, GtlWebsite.MaterialServiceReference.IMaterialService {
        
        public MaterialServiceClient() {
        }
        
        public MaterialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool GetMaterials(string materialTitle, string author, int numOfRecords, int isbn, int jobStatus) {
            return base.Channel.GetMaterials(materialTitle, author, numOfRecords, isbn, jobStatus);
        }
        
        public System.Threading.Tasks.Task<bool> GetMaterialsAsync(string materialTitle, string author, int numOfRecords, int isbn, int jobStatus) {
            return base.Channel.GetMaterialsAsync(materialTitle, author, numOfRecords, isbn, jobStatus);
        }
    }
}
