//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlWebsite.MaterialServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialServiceReference.IMaterialService")]
    public interface IMaterialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/GetMaterials", ReplyAction="http://tempuri.org/IMaterialService/GetMaterialsResponse")]
        Core.readAllMaterial[] GetMaterials(string materialTitle, string author, int numOfRecords, string isbn, string jobStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/GetMaterials", ReplyAction="http://tempuri.org/IMaterialService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<Core.readAllMaterial[]> GetMaterialsAsync(string materialTitle, string author, int numOfRecords, string isbn, string jobStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        bool CreateMaterial(int ssn, string isbn, string library, string author, string description, string title, string typeName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        System.Threading.Tasks.Task<bool> CreateMaterialAsync(int ssn, string isbn, string library, string author, string description, string title, string typeName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        bool DeleteMaterial(int ssn, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task<bool> DeleteMaterialAsync(int ssn, string isbn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialServiceChannel : GtlWebsite.MaterialServiceReference.IMaterialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialServiceClient : System.ServiceModel.ClientBase<GtlWebsite.MaterialServiceReference.IMaterialService>, GtlWebsite.MaterialServiceReference.IMaterialService {
        
        public MaterialServiceClient() {
        }
        
        public MaterialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Core.readAllMaterial[] GetMaterials(string materialTitle, string author, int numOfRecords, string isbn, string jobStatus) {
            return base.Channel.GetMaterials(materialTitle, author, numOfRecords, isbn, jobStatus);
        }
        
        public System.Threading.Tasks.Task<Core.readAllMaterial[]> GetMaterialsAsync(string materialTitle, string author, int numOfRecords, string isbn, string jobStatus) {
            return base.Channel.GetMaterialsAsync(materialTitle, author, numOfRecords, isbn, jobStatus);
        }
        
        public bool CreateMaterial(int ssn, string isbn, string library, string author, string description, string title, string typeName, int quantity) {
            return base.Channel.CreateMaterial(ssn, isbn, library, author, description, title, typeName, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> CreateMaterialAsync(int ssn, string isbn, string library, string author, string description, string title, string typeName, int quantity) {
            return base.Channel.CreateMaterialAsync(ssn, isbn, library, author, description, title, typeName, quantity);
        }
        
        public bool DeleteMaterial(int ssn, string isbn) {
            return base.Channel.DeleteMaterial(ssn, isbn);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMaterialAsync(int ssn, string isbn) {
            return base.Channel.DeleteMaterialAsync(ssn, isbn);
        }
    }
}
