//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtlWebsite.LoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginReference.ILoginController")]
    public interface ILoginController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginController/Login", ReplyAction="http://tempuri.org/ILoginController/LoginResponse")]
        string Login(int ssn, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginController/Login", ReplyAction="http://tempuri.org/ILoginController/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(int ssn, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginControllerChannel : GtlWebsite.LoginReference.ILoginController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginControllerClient : System.ServiceModel.ClientBase<GtlWebsite.LoginReference.ILoginController>, GtlWebsite.LoginReference.ILoginController {
        
        public LoginControllerClient() {
        }
        
        public LoginControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(int ssn, string password) {
            return base.Channel.Login(ssn, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(int ssn, string password) {
            return base.Channel.LoginAsync(ssn, password);
        }
    }
}
